### ISSUE TITLE
Handling misformat

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/xcproj#101]
## Context 🕵️‍♀️
Some projects might have an invalid format. When it happens, it's usually because a property is missing. That's something that can easily happen if you solve git conflicts on the project file, or whoever generates the project *(like the SPM)*, does it in a partial state, letting Xcode fulfill the missing attributes.

xcproj doesn't handle those cases and fails early, returning a parse error. This early error is very unexpected for a developer using the library.

## What 🌱
Discuss alternatives to improve this, being able to read those projects and fail later.

## Proposal 🎉
The only solution that I could come up with was using optionals for the properties. By doing that the reading wouldn't fail, but we'd have to deal with the optional all over the code base.

**Comment by pepibumur** [comment]
Ideas @xcodeswift/contributors ?

**Comment by artemnovichkov** [comment]
My suggestion in issue #79 - if you can't open a project in Xcode, you can't open it in xcproj.

**Comment by esttorhe** [comment]
I agree that if an expected property is missing we shouldn't definitely fail; perhaps clean up the error reporting and tell the user specifically what failed so it's easier for them to understand that is not the tools fault.

Eventually even hooking it up to what `CocoaPods` does and spit out a `Github`'s issues search on this repo to highlight possible solutions for the issue (e.g. check in `Xcode` that the file is not «missing»/unreferenced, etc)

**Comment by yonaskolb** [comment]
Yeah, I think the best approach is to improve the error messages first and then see how it plays out. Preemptively making many things optional is a decision we may regret later, as you can’t really come back from that.
It may even be worth suggestion running something like xclint over a project first, that highlights these sorts of issues and offers to fix them
