### ISSUE TITLE
Can't build for testing

### ISSUE THREAD

**Issue by artemnovichkov** [xcodeswift/xcproj#104]
## Context 🕵️‍♀️
Try to run tests in master with Xcode.

## What 🌱
Everything works fine in Terminal, but I have an errors in Xcode:
`Module 'xcproj' was not compiled for testing`

## Proposal 🎉
Fix it!

**Comment by toshi0383** [comment]
@artemnovichkov 
Try creating a scheme for `xcprojTests`.
Test runs correctly on my machine.

**Comment by pepibumur** [comment]
@artemnovichkov, try doing the following things:
- Delete the projects `rm -rf xcodeproj.xcodeproj xcproj.xcodeproj`.
- Generate the project again `swift package generate-xcodeproj`.
- Open the project and try to run the tests with Cmd + U.

Let me know if that works 😛

**Comment by artemnovichkov** [comment]
Both suggestions didn't work

**Comment by pepibumur** [comment]
Are you trying to import with `@testable` @artemnovichkov ?

**Comment by artemnovichkov** [comment]
The imports are already marked as testable.

**Comment by pepibumur** [comment]
Mmm weird, I'm running out of ideas. Did you try cloning the repo again? Are you using the last version of Xcode?

**Comment by artemnovichkov** [comment]
Xcode 9.0 (9A235), deleting and cloning again didn't work. Do you have the same errors?..

**Comment by pepibumur** [comment]
No, it's working and also on CI. Are you using the version of Swift that comes with Xcode?

**Comment by artemnovichkov** [comment]
Hm, works w/o errors on another MacBook...

**Comment by pepibumur** [comment]
Did you try reinstalling Xcode @artemnovichkov ?

**Comment by artemnovichkov** [comment]
Of course, no :)

**Comment by pepibumur** [comment]
Did you manage to solve this @artemnovichkov?

**Comment by artemnovichkov** [comment]
Actually, no. I didn't have a time.

**Comment by pepibumur** [comment]
No problem! It's not very high priority, just wanted to know if there was an update. Take your time 👍

**Comment by pepibumur** [comment]
I'll close it @artemnovichkov since the configuration seems to be ok and it's working on CI as well.
