### ISSUE TITLE
PBXProject decoding issue

### ISSUE THREAD

**Issue by enmiller** [xcodeswift/xcproj#108]
## Context 🕵️‍♀️
> While looking to update XcodeGen to use xcproj's latest 0.4.0 release, I ran into an issue while running XcodeGen's unit tests.  The failing test was due to `PBXProject`'s `Decodable` initialization method.

## What 🌱
> While decoding a `PBXProject` object, on line 127, there is the following
```swift
self.projectRoot = try container.decode(.projectRoot)
```
> However, the projectRoot entry in the project file is `projectRoot = "";`.   My assumption is that the `decode()` is interpreting the empty string as `nil` and is throwing an error.

## Proposal 🎉
> My proposal would be to use `decodeIfPresent()` instead
```swift
self.projectRoot = try container.decodeIfPresent(.projectRoot) ?? ""
```
> Since `projectRoot` is an optional property of `PBXProject`, it seems okay if the decoder returns nil here (or an empty string).

**Comment by enmiller** [comment]
Here is a snippet of the console output when running the XcodeGen unit tests after updating to xcproj 0.4.0 (minor formatting applied)
```
-> Test Project
  -> generates

 Test Project generates
  .build/checkouts/Spectre.git--7655155069707042687/Sources/Case.swift:31 
Unhandled error: keyNotFound(xcproj.PBXProject.(CodingKeys in _358E3F1E80A5A574E57C81A423F44836).projectRoot, 
Swift.DecodingError.Context(codingPath: [], 
debugDescription: "No value associated with key projectRoot (\"projectRoot\").", underlyingError: nil))
```

**Comment by yonaskolb** [comment]
@pepibumur, it seems some optional properties in #99 weren't made to use `decodeIfPresent`, such as this `projectRoot`

**Comment by pepibumur** [comment]
Good catch, it should be fixed [here](https://github.com/xcodeswift/xcproj/commit/712098a1a8bcbfdec03913d080bf76224bbe7e22) @enmiller. We'll release a new version on Saturday including the fix. Thanks for the report!
