### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by josefdolezal** [xcodeswift/xcproj#119]
## Context 🕵️‍♀️
Swift PM is a powerful dependency manager for macOS console applications. Projects which use Swift PM usually don't have `.xcodeproj` versioned in git repositories because it can be easily generated using `swift package generate-xcodeproj`. This command always creates a new project with structure based on a manifest file.

Since the project is not versioned, all custom project settings has to be made all over again once the project is generated - this includes custom targets, build phases and scheme settings.

I am in the middle of moving all project configurations into [Marathon scripts](https://github.com/JohnSundell/Marathon), which allows to manipulate with generated projects using `xcproj` library. Sadly, projects generated with Swift PM are not supported now.

Library version: `1.0.0`
Dependency manager: Swift PM / Marathon

## What 🌱
Currently, Xcode projects generated with Swift PM (using `swift package generate-xcodeproj`) are not supported in `XcodeProj` class. The initialiser now requires `*.xcworkspace` to be presented in `.xcodeproj` file. However, Swift PM creates only `.pbxproj`, `xcshareddata` and `.plist` files. This cause `XcodeProj` initialiser to fail and throw an error.

This can be easily fixed by opening the `.xcodeproj` and running `xcproj` script after that. Even though this fix works, it makes the project hard to maintain. This fix also can not be applied on CI servers since it take a while to start Xcode.

## Proposal 🎉
* Make `workspace ` property of `XcodeProj` class optional.
* Another option is to mock the `*.xcworkspace` if it is possible.

Since this is a breaking change which may not be implemented, we should at least add a note about this issue into project readme.

**Comment by pepibumur** [comment]
Hi @josefdolezal. Thanks for opening the issue. I think we should support opening SPM-generated projects in any way. I'll check your two proposals and maybe try to come up with another one so that we can discuss which one is more feasible.

**Comment by josefdolezal** [comment]
Thanks for s quick reply! Let me know if you come up with another solution, I would love to help fixing this one!

**Comment by pepibumur** [comment]
Here you go @josefdolezal https://github.com/xcodeswift/xcproj/pull/124
