### ISSUE TITLE
Build settings generated without quotation marks

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/xcproj#145]
## Context 🕵️‍♀️
Xcode generates the build settings that are strings adding quotation marks. When xcproj saves them, it doesn't add those quotation marks.

## What 🌱
![image](https://user-images.githubusercontent.com/663605/32538998-5b376894-c468-11e7-9477-57ecc08b02a7.png)

## Proposal 🎉
Update how the build settings are generated to include those quotation marks.

**Comment by yonaskolb** [comment]
I believe it only adds them if they contain special characters. And I think `/` is one of them. `$` may be too

**Comment by pepibumur** [comment]
Yeah we can have a list of those special characters and expand it as we find more cases.

**Comment by yonaskolb** [comment]
This CharacterSet should cover it
