### ISSUE TITLE
Automate some generation of code with Sourcery

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/xcproj#186]
## Context 🕵️‍♀️
As suggested by @toshi0383, there's some code that we can generate using Sourcery. Some examples of code that we can generate are:

- Constructor based on the properties.
- Equatable `func ==` implementation.
- Hashable.

## What 🌱
Introduce Sourcery into the codebase.

**Comment by yonaskolb** [comment]
And hashable.
We could then use the hash to do automatic references

**Comment by pepibumur** [comment]
Updated! What do you mean by *automatic references* @yonaskolb ?

**Comment by yonaskolb** [comment]
Well we could let xcproj automatically create references based on each objects contents as opposed to making users manually use the generator.
So when adding an object, the reference could be left out and then given an automatic reference. On writing (because the objects are mutable) it could then create a deterministic reference using all the properties, or  hashable, or a hand selected properties

**Comment by pepibumur** [comment]
Great idea! I think the less developers have to worry about these things the better. It should allow them to specify the reference if they want to though. I'll move the idea to an actionable issue that we can work on.

**Comment by LinusU** [comment]
Swift 4.1 supports automatically generating Hashable and Equatable now 🙌 🚀 

This could still be nice for initialisers based on the properties though 🤔

**Comment by LinusU** [comment]
Yes! 🎉 

https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md

**Comment by pepibumur** [comment]
I opened an issue to tackle this @LinusU, https://github.com/xcodeswift/xcproj/issues/248. If you are interested in working on it feel free to assign it to you and move it forward. We had some issues with our conformances in the past (missing properties) so this should help with all those issues.

**Comment by pepibumur** [comment]
Closing this one in favour of [this other issue](https://github.com/xcodeswift/xcproj/issues/248)
