### ISSUE TITLE
can't parse a demo with pod

### ISSUE THREAD

**Issue by iOSleep** [xcodeswift/xcproj#206]
## Context 🕵️‍♀️
> I just new a xcode project, add a podfile and install it by cocoapods. Then I find  can't be parse.

## What 🌱
> 
my pod version: `1.4.0.rc.1`
my xcode version: 9.2

```swift
let proj = try XcodeProj.init(path: path.absolute())
```
it pause in this place
![image](https://user-images.githubusercontent.com/26478957/34320934-655f3974-e83e-11e7-8e94-6c94721bbd81.png)

end get error info in console
![image](https://user-images.githubusercontent.com/26478957/34320942-afb128a2-e83e-11e7-83ea-1db430897ee3.png)

[the trouble xcodeproj file](https://github.com/xcodeswift/xcproj/files/1584252/TestDemo.xcodeproj.zip)

**Comment by yonaskolb** [comment]
Hi @iOSleep 
This was fixed in 1.3.0 https://github.com/xcodeswift/xcproj/releases/tag/1.3.0
From your screenshot it looks like you are using 0.4.1

**Comment by pepibumur** [comment]
Let us know if it works @iOSleep 😛

**Comment by iOSleep** [comment]
it works thanks~
