### ISSUE TITLE
GroupAddingOptions.withoutFolder is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by fuzza** [xcodeswift/xcproj#231]
## Context 🕵️‍♀️
**xcproj version**: 4.0.0
**Task**: Trying to add a PBXGroup that is not referenced to a real folder.

## What 🌱

There is a public struct `GroupAddingOptions` that is used to specify additional options for PBXGroup creation. 
The struct contains an internal constant `.withoutFolder` which seem to be designed for a public use as a parameter for a public `addGroup(named:to:options:)` method declared in `PBXProjObjects+Helpers`. 
As a result, from public API standpoint, there is no clear way to specify group adding options.

## Proposal 🎉
To decide whether permission level for this property should be changed to `public` or not. 
Please let me know if you want me to provide a fix.

**Comment by pepibumur** [comment]
It should be public @fuzza 😛. Feel free to open a PR with the change.
