### ISSUE TITLE
Leverage Swift 4.1 Hashable and Equatable conformance synthesizing

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/xcproj#248]
## Context 🕵️‍♀️
As @LinusU pointed out, with Swift 4.1 we get [Hashable and Equatable conformance](https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md) out of the box so we don't need to manually define it.

## What 🌱
We can remove our custom conformance and use the synthesizing the language gives us.

## Proposal 🎉
Just remove some unnecessary code 😬

**Comment by yonaskolb** [comment]
Sorry, but I believe auto `Equatable` and `Hashable` is only for value types, not classes

**Comment by pepibumur** [comment]
You are right, I'll reopen the other one.
![image](https://user-images.githubusercontent.com/663605/38362428-214d10ec-38d1-11e8-975d-3cbfb5b171ff.png)
