### ISSUE TITLE
Conform Equatable from XCScheme

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/xcproj#252]
## Context 🕵️‍♀️
`XCScheme` and all the associated models are not equatable. Writing the conformance manually was pain in the ass, but now with Sourcery we can generate it.

## What 🌱
Make XCScheme models conform Equatable using Sourcery.

**Comment by yonaskolb** [comment]
Duplicate of #200

**Comment by pepibumur** [comment]
You are right, I'll close this one.
