### ISSUE TITLE
Names of linked frameworks

### ISSUE THREAD

**Issue by artemnovichkov** [xcodeswift/xcproj#254]
## Context 🕵️‍♀️
I'm developing [Carting](https://github.com/artemnovichkov/Carting) and in next major release I want to rewrite project parsing logic with xcproj.

## What 🌱
I want to get a names of linked frameworks for every target, but I didn't API for it. Here is my test code:
```swift
let project = try XcodeProj(pathString: path)
for (_, target) in project.pbxproj.objects.nativeTargets {
    let frameworksBuildPhase = project.pbxproj.objects.frameworksBuildPhases.first { (key, _) in
        target.buildPhases.contains(key)
    }
    print(frameworksBuildPhase!.value.files)
}
```
I got only refs for frameworks.

**Comment by artemnovichkov** [comment]
I'm not sure I have enough time, but I'm ready to start it. Could you please tell me how I can get the names for framework references with current xcproj implementation?

**Comment by pepibumur** [comment]
Sure, no worries. I can do that, I just tried to explain you why it's not possible right now. So in order to do that with the current implementation:

```swift
func likedFrameworks(targetName: String, project: PBXProj) -> [PBXFileReference] {
    guard let target = project.objects.targets(named: targetName).first else { return [] }
    guard let frameworksBuildPhase: PBXFrameworksBuildPhase = project.objects.frameworksBuildPhases.filter({ (key, phase) in
        target.object.buildPhases.contains(key)
    }).first?.value else { return [] }
    let buildFiles = frameworksBuildPhase.files.compactMap({ project.objects.buildFiles[$0] }).compactMap({ $0.fileRef })
    return buildFiles.compactMap({ project.objects.fileReferences[$0] })
}
````
That should give you the linked frameworks for any target.

**Comment by artemnovichkov** [comment]
Got it, thank you!
