### ISSUE TITLE
Lack of Examples

### ISSUE THREAD

**Issue by Daltron** [xcodeswift/xcproj#44]
This project looks like it has great potential and I'm really trying to integrate it into one of my own swift command line tools, but the lack of examples/documentation makes it extremely difficult to use and understand. The README shows how to read and write, but it lacks the most important feature of all in my opinion, modifying components of the project. 

Is there any plans to add more examples in the future?
Thanks! 😄

**Comment by pepibumur** [comment]
That's a very good point @Daltron. I'll work on adding more documentation to the project.

**Comment by pepibumur** [comment]
@Daltron I've updated the README with a [*How to use*](https://github.com/yonaskolb/XcodeGen/issues/51#issuecomment-331178779) section. Do you think it helps or would you add anything else?

**Comment by Daltron** [comment]
@pepibumur A diagram is nice but it would be even better if the README showed specific examples on how to modify the most common operations such as creating a group, creating a file, adding a file to a group, etc...

**Comment by Daltron** [comment]
Hey guys! 😄 The examples have come a long way since I first opened this issue so thank you for that! I'm looking to finish what I once originally had conceptualized now that I can do what I am wanting to do :)

**Comment by pepibumur** [comment]
Nice! Feel free to ping us if you get stuck with anything. We're happy to help you.
