### ISSUE TITLE
Mapping error in PBXFileReference section

### ISSUE THREAD

**Issue by artemnovichkov** [xcodeswift/xcproj#79]
## Context
I tried to parse one of my projects.

## What
Simple initialization:
```swift
let project = try XcodeProj(path: "ProjectName.xcodeproj")
```
Related to the error: `[UnboxError] An error occurred while unboxing path "fileRef": The key "fileRef" is missing.`
As I understand, the problem is here:
```
0AEBC6F01F2F0F28000441DB /* VideoPickerPageInteractor.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = VideoPickerPageInteractor.swift; sourceTree = "<group>"; };
```

## Proposal
Update mapping of `PBXFileReference` project to handle this case.

**Comment by pepibumur** [comment]
I don't think it's because of the `PBXFileReference` model. It must be a model that has a `fileRef` property that is expected to be non-nil and should be nil. Would you mind checking which one is?

**Comment by artemnovichkov** [comment]
I watched an exception in `PBXFileReference` init with a dictionary:
```["isa": PBXFileReference, 
"lastKnownFileType": sourcecode.swift, 
"path": VideoPickerPageInteractor.swift, 
"sourceTree": <group>, 
"fileEncoding": 4]
```

**Comment by pepibumur** [comment]
@artemnovichkov I've checked which objects contain a `fileRef` property, and only the `PBXBuildFile` has. As far as I know, the only way to get into that situation where one of your build files doesn't have a reference is by removing the property while solving merge conflicts. Could you check if that's the case? You can open of those projects, go to build phases, and see if any of the files appear in a translucent color (it's missing). 
I'm not sure if this is something xcproj should handle, but rather, throw a more explicit error telilng you what's wrong. What do you think? cc @yonaskolb

**Comment by artemnovichkov** [comment]
@pepibumur Makes sense. I didn't think about it. My thought about this issue - if you can open a project in Xcode, you can open it in xcproj. But of course it's need to show this error to users. Anyway, I'll check the project 👍.

**Comment by pepibumur** [comment]
This issue will be fixed once we come up with a strategy to handle misformatted projects, https://github.com/xcodeswift/xcproj/issues/101. Closing it
