### ISSUE TITLE
Remove Unbox dependency

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/xcproj#83]
## Context
After the project [has been migrated to Swift 4](https://github.com/xcodeswift/xcproj/pull/84) we can remove the Unbox dependency and use the language encoding/decoding feature.

## What
Use the language encoding/decoding feature instead of Unbox.

## Proposal
- Update all the models that support decoding.

**Comment by esttorhe** [comment]
Maybe we should update the description now that #84 was merged.
`Context` mentions #82 which ended up not being the «correct» one for this issue

**Comment by pepibumur** [comment]
Updated @esttorhe 😛
