### ISSUE TITLE
Add support for using xcproj on iOS projects during unit testing

### ISSUE THREAD

**Issue by BrianBatchelder** [xcodeswift/xcproj#89]
## Context
I work on an open-source iOS SDK. We consider our project file as part of our assets, and do some simple validation tests as part of our unit test suite. We'd like to be able to use xcproj for that validation, but the current limitation to macOS-only prevents CocoaPods from installing your pod.

What version of Xcode/Swift are you using? - 9/3.1
What operating system and processor architecture are you using? - macOS High Sierra for runningXcode. iOS / tvOS for SDK.
What did you do? - Tried to use CocoaPods to install xcproj
What did you expect to see? - Successful pod install
What did you see instead?
`The platform of the target 'MyAppTests' (iOS 10.0) is not compatible with 'xcodeproj (0.2.0)', which does not support 'ios'.`

## What
Couldn't use xcproj inside our unit tests.

## Proposal
Remove macOS-only limitation in xcproj. The limitation was introduced in [this commit](https://github.com/xcodeswift/xcproj/commit/9f6e8d6a32b9e5418de1613a42259351d67d0880).

**Comment by pepibumur** [comment]
@BrianBatchelder thanks for the proposal. I've opened a PR to support iOS in the podspec. Could you have a look and give feedback? Once merged you should be able to use it with your CocoaPods setup by specifying the commit on this repository. Next Saturday we'll release a new version and you'll be able to use the version instead.
