### ISSUE TITLE
Documentation link is not working

### ISSUE THREAD

**Issue by mukeshthawani** [xcodeswift/xcproj#90]
## What

Documentation link gives 404 error.

![screen shot 2017-09-29 at 11 55 16 pm](https://user-images.githubusercontent.com/5956714/31030154-f085be70-a571-11e7-8ab7-58988cda15fb.png)

**Comment by pepibumur** [comment]
Hey @mukeshthawani, where did you get the documentation link from?

**Comment by mukeshthawani** [comment]
It was in the Readme. Looks like now it's fixed.

Thanks :)
